---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/posts/{post_id}/comments":
    parameters:
    - name: post_id
      in: path
      description: post_id
      required: true
      schema:
        type: string
    get:
      summary: list comments
      responses:
        '201':
          description: Post created
        '200':
          description: successful
    post:
      summary: create comment
      parameters: []
      responses:
        '201':
          description: Post created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
  "/api/v1/posts":
    get:
      summary: list all posts
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                - id:
                    type: integer
                  title:
                    type: string
                  text:
                    type: string
        '406':
          description: unsupported accept header
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
